export const SCREEN_NAME = {
  entrance: 'entrance',
  login: 'login',
  signup: 'signup',
  otpVerification: 'otpVerification',
  forgotPassword: 'forgotPassword',
  setPassword: 'setPassword',
  dashboard: 'dashboard',
  indexScreen: 'indexScreen',
  splashScreen: 'splashScreen',
  voiceRecorder: 'voiceRecorder',
  setEmailAndUserName: 'setEmailAndUserName',
  onBoardingIndex: 'onBoardingIndex',
  personalDetails: 'personalDetails',
  skillDetails: 'skillDetails',
  searchScreen: 'searchScreen',
  voterList: 'voterList',
  voterDetails: 'voterDetails',
  electionList: 'electionList',
  addNewElection: 'addNewElection',
  electionVotersTab: 'electionVotersTab',
  appFilterScreen: 'appFilterScreen',
};
